version: "3.8"
   
services:
  postgres:
    image: 'postgres:9.6.20-alpine'
    restart: always
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432'

  django:
    labels:
      shipyard.before: 'poetry run python manage.py migrate'
      shipyard.route: '/'
    build: .
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres: