version: "3.8"
   
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  django:
    build: .
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres: