version: "3.8"
   
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  django:
    build: .
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres: