version: "3.8"
   
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    networks:
      django_network:
  django:
    labels:
      shipyard.before: 'poetry run python manage.py migrate'
      shipyard.route: '/'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
    build: .
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres:postgres
    networks:
      django_network:
networks:
  django_network:
volumes:
  postgres: